# Generated by Django 5.0.14 on 2025-10-01 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['kategori_adi'],
            },
        ),
        migrations.CreateModel(
            name='Tedarikci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=255, unique=True, verbose_name='Firma Adı')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
            ],
            options={
                'verbose_name': 'Tedarikçi',
                'verbose_name_plural': 'Tedarikçiler',
                'ordering': ['firma_adi'],
            },
        ),
        migrations.CreateModel(
            name='SatisFisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fis_no', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='Fiş No')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Tutar')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Satış Tarihi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='kullanici')),
            ],
            options={
                'verbose_name': 'Satış Fişi',
                'verbose_name_plural': 'Satış Fişleri',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('stok_no', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('urun_adi', models.CharField(max_length=200)),
                ('birim', models.CharField(choices=[('adet', 'Adet'), ('kg', 'Kilogram'), ('lt', 'Litre'), ('m', 'Metre'), ('m2', 'Metrekare'), ('paket', 'Paket')], default='adet', max_length=20, verbose_name='Birim')),
                ('barkod', models.CharField(blank=True, max_length=13, unique=True)),
                ('barkod_resim', models.ImageField(blank=True, null=True, upload_to='barkodlar/')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok_takip.kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['kategori', 'urun_adi'],
            },
        ),
        migrations.CreateModel(
            name='SatisFiyati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alim_fiyati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alım Fiyatı')),
                ('kar_orani', models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Kar Oranı %')),
                ('kdv', models.IntegerField(choices=[(1, '%1'), (10, '%10'), (20, '%20')], default=20, verbose_name='KDV Oranı')),
                ('iskonto_orani', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='İskonto Oranı %')),
                ('satis_fiyati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Satis Fiyatı')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok_takip.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Satış Fiyatı',
                'verbose_name_plural': 'Ürün Satış Fiyatları',
            },
        ),
        migrations.CreateModel(
            name='Satis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar')),
                ('birim_fiyat', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Birim Fiyat')),
                ('toplam_fiyat', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Toplam Fiyat')),
                ('fis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satislar', to='stok_takip.satisfisi', verbose_name='Fiş')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stok_takip.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Satış',
                'verbose_name_plural': 'Satışlar',
            },
        ),
        migrations.CreateModel(
            name='UrunYerlesimYeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.IntegerField(default=0, verbose_name='Miktar')),
                ('konum', models.CharField(max_length=50, verbose_name='Konum')),
                ('urun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stok_takip.urun')),
            ],
            options={
                'verbose_name': 'Ürün Yerleşim Yeri',
                'verbose_name_plural': 'Ürün Yerleşim Yerleri',
                'ordering': ['konum'],
            },
        ),
    ]
