# Generated by Django 5.0.14 on 2025-10-02 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok_takip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urunyerlesimyeri',
            options={'ordering': ['son_kullanma_tarihi', 'konum'], 'verbose_name': 'Ürün Yerleşim Yeri', 'verbose_name_plural': 'Ürün Yerleşim Yerleri'},
        ),
        migrations.AddField(
            model_name='urunyerlesimyeri',
            name='giris_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Giriş Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urunyerlesimyeri',
            name='lot_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lot/Parti No'),
        ),
        migrations.AddField(
            model_name='urunyerlesimyeri',
            name='son_kullanma_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Son Kullanma Tarihi'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='barkod',
            field=models.CharField(blank=True, default='869000000100', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='urun',
            name='stok_no',
            field=models.CharField(default='287900000100', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
