# Generated by Django 5.0.14 on 2025-10-02 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok_takip', '0002_alter_urunyerlesimyeri_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunyerlesimyeri',
            name='urun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yerlesimler', to='stok_takip.urun'),
        ),
    ]
