# Generated by Django 5.0.14 on 2025-10-02 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok_takip', '0003_alter_urunyerlesimyeri_urun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='satis',
            options={},
        ),
        migrations.CreateModel(
            name='TedarikciIade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.IntegerField(verbose_name='İade Miktarı')),
                ('iade_nedeni', models.TextField(verbose_name='İade Nedeni')),
                ('durum', models.CharField(choices=[('beklemede', 'İade Beklemede'), ('kabul', 'Tedarikçi Kabul Etti'), ('red', 'Tedarikçi Reddetti'), ('degisim', 'Yenisiyle Değiştirildi')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('iade_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='İade Tarihi')),
                ('cozum_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Çözüm Tarihi')),
                ('not_lar', models.TextField(blank=True, verbose_name='Notlar')),
                ('tedarikci', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stok_takip.tedarikci', verbose_name='Tedarikçi')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stok_takip.urun', verbose_name='Ürün')),
                ('yerlesim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stok_takip.urunyerlesimyeri', verbose_name='Lot/Yerleşim')),
            ],
            options={
                'verbose_name': 'Tedarikçi İade',
                'verbose_name_plural': 'Tedarikçi İadeler',
                'ordering': ['-iade_tarihi'],
            },
        ),
    ]
