# Generated by Django 5.0.14 on 2025-10-02 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok_takip', '0004_alter_satis_options_tedarikciiade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusteriIade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.IntegerField(verbose_name='İade Miktarı')),
                ('iade_nedeni', models.TextField(verbose_name='İade Nedeni')),
                ('durum', models.CharField(choices=[('beklemede', 'İade Beklemede'), ('onaylandi', 'İade Onaylandı'), ('reddedildi', 'İade Reddedildi')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('cozum_tipi', models.CharField(blank=True, choices=[('para', 'Para İadesi'), ('degisim', 'Ürün Değişimi'), ('kupon', 'İndirim Kuponu')], max_length=20, verbose_name='Çözüm Tipi')),
                ('iade_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İade Tutarı')),
                ('iade_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='İade Tarihi')),
                ('islem_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='İşlem Tarihi')),
                ('not_lar', models.TextField(blank=True, verbose_name='Notlar')),
                ('satis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stok_takip.satis', verbose_name='Satış Kaydı')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stok_takip.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Müşteri İade',
                'verbose_name_plural': 'Müşteri İadeler',
                'ordering': ['-iade_tarihi'],
            },
        ),
    ]
