# Generated by Django 5.0.14 on 2025-10-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok_takip', '0005_musteriiade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakiye', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Güncel Bakiye')),
                ('son_guncelleme', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Kasa',
                'verbose_name_plural': 'Kasa',
            },
        ),
    ]
