# Generated by Django 5.0.14 on 2025-10-02 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok_takip', '0006_kasa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlisFisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fis_no', models.CharField(max_length=50, unique=True, verbose_name='Fiş/Fatura No')),
                ('lot_no', models.CharField(blank=True, max_length=50, verbose_name='Lot No')),
                ('son_kullanma_tarihi', models.DateField(blank=True, null=True, verbose_name='Son Kullanma Tarihi')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Tutar')),
                ('fis_tarihi', models.DateField(verbose_name='Fiş Tarihi')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('tedarikci', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stok_takip.tedarikci', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Alış Fişi',
                'verbose_name_plural': 'Alış Fişleri',
                'ordering': ['-fis_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='AlisDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.IntegerField(verbose_name='Miktar')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat')),
                ('toplam_fiyat', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Toplam Fiyat')),
                ('konum', models.CharField(max_length=50, verbose_name='Yerleşim Konumu')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stok_takip.urun', verbose_name='Ürün')),
                ('fis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='stok_takip.alisfisi', verbose_name='Alış Fişi')),
            ],
            options={
                'verbose_name': 'Alış Detayı',
                'verbose_name_plural': 'Alış Detayları',
            },
        ),
        migrations.CreateModel(
            name='OdemeKasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odeme_tipi', models.CharField(choices=[('fatura', 'Fatura'), ('kira', 'Kira'), ('maas', 'Maaş'), ('vergi', 'Vergi'), ('elektrik', 'Elektrik'), ('su', 'Su'), ('internet', 'İnternet'), ('kargo', 'Kargo'), ('diger', 'Diğer')], max_length=20, verbose_name='Ödeme Tipi')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('odeme_tarihi', models.DateField(verbose_name='Ödeme Tarihi')),
                ('islem_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-odeme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SatisKasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('islem_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Tarihi')),
                ('satis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stok_takip.satis', verbose_name='Satış')),
            ],
            options={
                'verbose_name': 'Satış Kasa Hareketi',
                'verbose_name_plural': 'Satış Kasa Hareketleri',
                'ordering': ['-islem_tarihi'],
            },
        ),
    ]
