# Generated by Django 5.0.14 on 2025-10-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok_takip', '0007_alisfisi_alisdetay_odemekasa_satiskasa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alisfisi',
            name='son_kullanma_tarihi',
        ),
        migrations.AddField(
            model_name='alisdetay',
            name='son_kullanma_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Son Kullanma Tarihi'),
        ),
    ]
